FROM nginx:alpine

# Copy TLS nginx config
COPY nginx/default-ssl.conf /etc/nginx/conf.d/default.conf

# Copy SSL certs
COPY nginx/selfsigned.crt /etc/ssl/certs/selfsigned.crt
COPY nginx/selfsigned-rsa.key /etc/ssl/private/selfsigned-rsa.key